### ISSUE TITLE
In PDF, vertical gaps occur where connector is attached to node

### ISSUE THREAD

**Issue by BAndrews22** [pepijn-devries/ggsankeyfier#13]
When looking at the plot in RStudio, the connectors perfectly take up the entire space of the node.
But when I save it as a PDF, there are substantial vertical gaps between the connectors where they are attaching to the node.
Thanks for the great package!

**Comment by pepijn-devries** [comment]
Hi @BAndrews22,

This happens when:
  * You resize the plotting device after the plot was generated
    * *Solution*: don't save your plot from the RStudio device, but plot it directly to a pdf device in your code
  * Your plotting area has an inappropriate aspect ratio (i.e., too narrow)
    * *Solution*: make sure your plot is wide enough

If this does not solve your issue, please reopen this issue and file a more detailed report including a (reprex)[https://reprex.tidyverse.org/].

Cheers,

Pepijn
